### ISSUE TITLE
"Getting Started" directions don't work on OSX

### ISSUE THREAD

**Issue by keithlayne** [purescript-contrib/purescript-book#396]
This is not a show-stopper for me but I'm a little blown away that you have two scripts that you instruct users to run after cloning this repo to follow along, and they are a little crazy, all things considered.

Here's my list of complaints:

- Removing anchors doesn't work on Mac, because it looks like it's dependent on a gnu find feature (extended regexes)
- The anchor script is completely overengineered. A quick grep shows that `"ANCHOR"` only appears in the repo in the lines that should be deleted in `exercises` and that script.
- Perl?  Really?  I have perl installed for other reasons, but that's a pretty weird dependency for a book about another language.
- The earlier step had you install node and some npms...that's guaranteed to be on the system now, and these tasks are trivial, so that would be better.
- `sed` is still a better choice for all these tasks you could do `sed -i.nuke && find ./exercises -type f -name "*.nuke" -delete` or something like that.
- Windows?  I don't do windows myself, but I feel like there shouldn't be anything stopping those users from following along.

I've already spent more time complaining about this than it would take to fix it :( Sorry about that.

Forget all that, here's an actual suggestion that I might contribute:

When changes are merged into master, run a GH action that applies the instructions and pushes them to a branch that you can point users at. This is simple, would run in a controlled environment (linux, with gnu find/sed and perl installed), and would lower the bar that much more for your readers.

**Comment by keithlayne** [comment]
I think it would go something like this:

1. Create a branch, call it `follow-along` or something.
1. Allow GH actions to push...I haven't done this personally, but I know it's a thing.
1. Add an action that's something like this:
    ```yaml
    name: Update follow-along branch
    on:
      push:
        branches: [master]
      pull_request:
    jobs:
      update:
        runs-on: ubuntu-latest
        steps:
          - Check it out 
            uses: actions/checkout@v2
          - name: Update the thing
            run: |
              ./scripts/resetSolutions.sh
              ./scripts/removeAnchors.sh
              git add --all
              git commit --message "Some really sweet message here"
              git push origin HEAD:follow-along
    ```
1. Update the instructions in the book to instead check out the branch that's totally ready for your readers to play with!
